services:
    app:
        image: webdevops/php-apache:8.3
        container_name: recruitis-app
        ports:
            - "3030:80"
        volumes:
            - .:/app
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_DISPLAY_ERRORS=1
            - PHP_MEMORY_LIMIT=512M
